# dx.tbls <- c(
#     "dx_200_alinity_s_calcurve",
#     "dx_200_alinity_s_experimentprocessing",
#     "dx_200_alinity_s_iarm",
#     "dx_200_alinity_s_icbmotormove",
#     "dx_200_alinity_s_inductionheaterrunprofileresponsedata",
#     "dx_200_alinity_s_inductionheaterwaveformdata",
#     "dx_200_alinity_s_instrumentactivity",
#     "dx_200_alinity_s_itvdata",
#     "dx_200_alinity_s_liquidwasterawdata",
#     "dx_200_alinity_s_liquidwastescoredata",
#     "dx_200_alinity_s_lld",
#     "dx_200_alinity_s_lldnoise",
#     "dx_200_alinity_s_messagehistory",
#     "dx_200_alinity_s_mndhistory",
#     "dx_200_alinity_s_mndrecorddata",
#     "dx_200_alinity_s_navigateservicedata",
#     "dx_200_alinity_s_opticsdispensepmresultdata",
#     "dx_200_alinity_s_opticshighresolutiondata",
#     "dx_200_alinity_s_oshealthmonitoringdata",
#     "dx_200_alinity_s_pipettordispensepmrawdata",
#     "dx_200_alinity_s_pipettordispensepmscoredata",
#     "dx_200_alinity_s_pipettoroperation",
#     "dx_200_alinity_s_pipettorpm",
#     "dx_200_alinity_s_pipettorpmrawdata",
#     "dx_200_alinity_s_pipettorsyringebacklashdata",
#     "dx_200_alinity_s_pipettorwashpm",
#     "dx_200_alinity_s_pipettorwashpmrawdata",
#     "dx_200_alinity_s_pipettorwashpmscoredata",
#     "dx_200_alinity_s_processpath",
#     "dx_200_alinity_s_reagentoperation",
#     "dx_200_alinity_s_result",
#     "dx_200_alinity_s_sampleoperation",
#     "dx_200_alinity_s_scripting",
#     "dx_200_alinity_s_systemoperation",
#     "dx_200_alinity_s_teknicmotor",
#     "dx_200_alinity_s_temperaturedata",
#     "dx_200_alinity_s_triggerpretriggerrawdata",
#     "dx_200_alinity_s_triggerpretriggerscoredata",
#     "dx_200_alinity_s_wampmresultdata",
#     "dx_200_alinity_s_washstationevacuationpmresultdata",
#     "dx_200_alinity_s_washzoneaspirationpmrawdata",
#     "dx_200_alinity_s_washzoneaspirationpmscoredata",
#     "dx_200_alinity_s_washzonedispensepmresultdata",
#     "dx_200_alinity_s_washzonedispensepmscoredata",
#     "dx_200_alinity_s_washzoneinitvacuumpressuredata",
#     "dx_205_205",
#     "dx_205_assayactivity",
#     "dx_205_assayactivitycc",
#     "dx_205_calcurve",
#     "dx_205_calibrationresultcompletion",
#     "dx_205_ccaspirationpm",
#     "dx_205_ccbulksolutionconsumeddata",
#     "dx_205_cccuvettewashwatervolumedata",
#     "dx_205_ccdispensepm",
#     "dx_205_ccphotodata",
#     "dx_205_ccpipettorpmrawdata",
#     "dx_205_ccreagentaspirationotherdata",
#     "dx_205_ccreagentaspirationpcidata",
#     "dx_205_ccreagentcarouselcoolertemperaturedata",
#     "dx_205_ccreagentcarouselteknicmotordata",
#     "dx_205_ccreagentdispenseotherdata",
#     "dx_205_ccreagentdispensepcidata",
#     "dx_205_ccreagentwashotherdata",
#     "dx_205_ccreagentwashpcidata",
#     "dx_205_ccsampleaspirationotherdata",
#     "dx_205_ccsampleaspirationpcidata",
#     "dx_205_ccsampledispenseotherdata",
#     "dx_205_ccsampledispensepcidata",
#     "dx_205_ccsamplewashotherdata",
#     "dx_205_ccsamplewashpcidata",
#     "dx_205_ccwashpm",
#     "dx_205_constituentdata",
#     "dx_205_experimentprocessing",
#     "dx_205_heaterdutycycledata",
#     "dx_205_iarm",
#     "dx_205_icbmotormove",
#     "dx_205_inductionheaterrunprofileresponsedata",
#     "dx_205_inductionheaterwaveformdata",
#     "dx_205_instrumentactivity",
#     "dx_205_itvdata",
#     "dx_205_lld",
#     "dx_205_lldcc",
#     "dx_205_lldnoise",
#     "dx_205_lldnoisedata",
#     "dx_205_mndhistory",
#     "dx_205_mndrecorddata",
#     "dx_205_navigateservicedata",
#     "dx_205_opticsrawdata",
#     "dx_205_oshealthmonitoringdata",
#     "dx_205_pipettorsyringebacklashdata",
#     "dx_205_pmrawdata",
#     "dx_205_reagentcoolerdata",
#     "dx_205_reagentoperation",
#     "dx_205_scripting",
#     "dx_205_teknicmotor",
#     "dx_205_temperaturedata",
#     "dx_205_vacuumpressuredata",
#     "dx_205_wambulkdata",
#     "dx_205_wamdata",
#     "dx_210_210",
#     "dx_210_assayactivity",
#     "dx_210_assayactivitycc",
#     "dx_210_calcurve",
#     "dx_210_calibrationresultcompletion",
#     "dx_210_ccaspirationpm",
#     "dx_210_ccbulksolutionconsumeddata",
#     "dx_210_ccbulksolutionmonitordata",
#     "dx_210_ccbulksolutionusagestatusdata",
#     "dx_210_cccuvettewashwatervolumedata",
#     "dx_210_ccdispensepm",
#     "dx_210_cclampmonitordata",
#     "dx_210_ccopticsadjusttriggersensordata",
#     "dx_210_ccphotodata",
#     "dx_210_ccpipettorpmrawdata",
#     "dx_210_ccreagentaspirationotherdata",
#     "dx_210_ccreagentaspirationpcidata",
#     "dx_210_ccreagentcarouselcoolertemperaturedata",
#     "dx_210_ccreagentcarouselteknicmotordata",
#     "dx_210_ccreagentdispenseotherdata",
#     "dx_210_ccreagentdispensepcidata",
#     "dx_210_ccreagentwashotherdata",
#     "dx_210_ccreagentwashpcidata",
#     "dx_210_ccsampleaspirationotherdata",
#     "dx_210_ccsampleaspirationpcidata",
#     "dx_210_ccsampledispenseotherdata",
#     "dx_210_ccsampledispensepcidata",
#     "dx_210_ccsamplewashotherdata",
#     "dx_210_ccsamplewashpcidata",
#     "dx_210_ccwashpm",
#     "dx_210_ccwaterbathrefilldata",
#     "dx_210_constituentdata",
#     "dx_210_experimentprocessing",
#     "dx_210_heaterdutycycledata",
#     "dx_210_iarm",
#     "dx_210_icbmotormove",
#     "dx_210_instrumentactivity",
#     "dx_210_itvdata",
#     "dx_210_lld",
#     "dx_210_lldcc",
#     "dx_210_messagehistory",
#     "dx_210_mndhistory",
#     "dx_210_mndrecorddata",
#     "dx_210_navigateservicedata",
#     "dx_210_opticsrawdata",
#     "dx_210_oshealthmonitoringdata",
#     "dx_210_pmevent",
#     "dx_210_pmrawdata",
#     "dx_210_reagentcoolerdata",
#     "dx_210_reagentoperation",
#     "dx_210_scripting",
#     "dx_210_teknicmotor",
#     "dx_210_temperaturedata",
#     "dx_210_vacuumpressuredata",
#     "dx_210_wambulkdata",
#     "dx_210_wamdata",
#     "dx_214_214",
#     "dx_214_assayactivity",
#     "dx_214_assayactivitycc",
#     "dx_214_calcurve",
#     "dx_214_calibrationresultcompletion",
#     "dx_214_ccaspirationpm",
#     "dx_214_ccbulksolutionconsumeddata",
#     "dx_214_ccbulksolutionmonitordata",
#     "dx_214_cccuvettewashwatervolumedata",
#     "dx_214_ccdispensepm",
#     "dx_214_cclampmonitordata",
#     "dx_214_ccopticsadjusttriggersensordata",
#     "dx_214_ccphotodata",
#     "dx_214_ccpipettorpmrawdata",
#     "dx_214_ccreagentaspirationotherdata",
#     "dx_214_ccreagentaspirationpcidata",
#     "dx_214_ccreagentcarouselcoolertemperaturedata",
#     "dx_214_ccreagentcarouselteknicmotordata",
#     "dx_214_ccreagentdispenseotherdata",
#     "dx_214_ccreagentdispensepcidata",
#     "dx_214_ccreagentwashotherdata",
#     "dx_214_ccreagentwashpcidata",
#     "dx_214_ccsampleaspirationotherdata",
#     "dx_214_ccsampleaspirationpcidata",
#     "dx_214_ccsampledispenseotherdata",
#     "dx_214_ccsampledispensepcidata",
#     "dx_214_ccsamplewashotherdata",
#     "dx_214_ccsamplewashpcidata",
#     "dx_214_ccwashpm",
#     "dx_214_ccwaterbathrefilldata",
#     "dx_214_constituentdata",
#     "dx_214_experimentprocessing",
#     "dx_214_heaterdutycycledata",
#     "dx_214_iarm",
#     "dx_214_icbmotormove",
#     "dx_214_instrumentactivity",
#     "dx_214_itvdata",
#     "dx_214_lld",
#     "dx_214_lldcc",
#     "dx_214_lldnoise",
#     "dx_214_messagehistory",
#     "dx_214_mndhistory",
#     "dx_214_mndrecorddata",
#     "dx_214_navigateservicedata",
#     "dx_214_opticsrawdata",
#     "dx_214_oshealthmonitoringdata",
#     "dx_214_pipettorsyringebacklashdata",
#     "dx_214_pmrawdata",
#     "dx_214_reagentcoolerdata",
#     "dx_214_reagentoperation",
#     "dx_214_result",
#     "dx_214_scripting",
#     "dx_214_teknicmotor",
#     "dx_214_temperaturedata",
#     "dx_214_vacuumpressuredata",
#     "dx_214_wambulkdata",
#     "dx_214_wamdata",
#     "dx_215_alinity_h_calibrationfactorbodyfluid",
#     "dx_215_alinity_h_calibrationfactorwholeblood",
#     "dx_215_alinity_h_dilutionfactorbodyfluid",
#     "dx_215_alinity_h_dilutionfactorwholeblood",
#     "dx_215_alinity_h_maint",
#     "dx_215_alinity_h_mvavgplt",
#     "dx_215_alinity_h_mvavgrbc",
#     "dx_215_alinity_h_mvavgrbcoptical",
#     "dx_215_alinity_h_mvavgretc",
#     "dx_215_alinity_h_mvavgretcoptical",
#     "dx_215_alinity_h_mvavgwbc",
#     "dx_215_alinity_h_mvavgwbcoptical",
#     "dx_215_alinity_h_mvavgxb",
#     "dx_215_alinity_h_reagents",
#     "dx_215_alinity_h_results",
#     "dx_215_alinity_h_supplies",
#     "dx_215_alinity_h_system",
#     "dx_640_alinity_m_ampdetect",
#     "dx_640_alinity_m_ampdetectcontaminationdata",
#     "dx_640_alinity_m_calcurve",
#     "dx_640_alinity_m_internalcontrolbaselineddata",
#     "dx_640_alinity_m_internalcontrolmaxratiodata",
#     "dx_640_alinity_m_internalcontrolnormalizeddata",
#     "dx_640_alinity_m_internalcontrolreferencedata",
#     "dx_640_alinity_m_internalcontrolsignaldata",
#     "dx_640_alinity_m_messagehistory",
#     "dx_640_alinity_m_mndhistory",
#     "dx_640_alinity_m_mndrecorddata",
#     "dx_640_alinity_m_reagentoperation",
#     "dx_640_alinity_m_result",
#     "dx_640_alinity_m_resultinternalcontrol",
#     "dx_640_alinity_m_resulttargets",
#     "dx_640_alinity_m_scripting",
#     "dx_640_alinity_m_targetanalysisbaselineddata",
#     "dx_640_alinity_m_targetanalysisnormalizeddata",
#     "dx_640_alinity_m_targetanalysisreferencedata",
#     "dx_640_alinity_m_targetanalysissignaldata",
#     "dx_dim_customer_vw",
#     "dx_dim_entity_vw",
#     "dx_dim_hierarchy_vw",
#     "dx_dim_product_hierarchy_vw",
#     "dx_dim_tods_add_instrument_mstr",
#     "dx_pub_dev_wamdata",
#     "dx_205_messagehistory",
#     "dx_205_pmevent",
#     "dx_205_result",
#     "dx_210_result",
#     "dx_214_pmevent"
# )
#

# dx.tbls <- c(
#     "dx_205_alinity_i_assayactivity",
#     "dx_205_alinity_i_assayactivitycc",
#     "dx_205_alinity_i_calcurve",
#     "dx_205_alinity_i_calibrationresultcompletion",
#     "dx_205_alinity_i_ccaspirationpm",
#     "dx_205_alinity_i_ccbulksolutionconsumeddata",
#     "dx_205_alinity_i_cccuvettewashwatervolumedata",
#     "dx_205_alinity_i_ccdispensepm",
#     "dx_205_alinity_i_ccphotodata",
#     "dx_205_alinity_i_ccpipettorpmrawdata",
#     "dx_205_alinity_i_ccreagentaspirationotherdata",
#     "dx_205_alinity_i_ccreagentaspirationpcidata",
#     "dx_205_alinity_i_ccreagentcarouselcoolertemperaturedata",
#     "dx_205_alinity_i_ccreagentcarouselteknicmotordata",
#     "dx_205_alinity_i_ccreagentdispenseotherdata",
#     "dx_205_alinity_i_ccreagentdispensepcidata",
#     "dx_205_alinity_i_ccreagentwashotherdata",
#     "dx_205_alinity_i_ccreagentwashpcidata",
#     "dx_205_alinity_i_ccsampleaspirationotherdata",
#     "dx_205_alinity_i_ccsampleaspirationpcidata",
#     "dx_205_alinity_i_ccsampledispenseotherdata",
#     "dx_205_alinity_i_ccsampledispensepcidata",
#     "dx_205_alinity_i_ccsamplewashotherdata",
#     "dx_205_alinity_i_ccsamplewashpcidata",
#     "dx_205_alinity_i_ccwashpm",
#     "dx_205_alinity_i_constituentdata",
#     "dx_205_alinity_i_experimentprocessing",
#     "dx_205_alinity_i_heaterdutycycledata",
#     "dx_205_alinity_i_iarm",
#     "dx_205_alinity_i_icbmotormove",
#     "dx_205_alinity_i_inductionheaterrunprofileresponsedata",
#     "dx_205_alinity_i_inductionheaterwaveformdata",
#     "dx_205_alinity_i_instrumentactivity",
#     "dx_205_alinity_i_itvdata",
#     "dx_205_alinity_i_lld",
#     "dx_205_alinity_i_lldcc",
#     "dx_205_alinity_i_lldnoise",
#     "dx_205_alinity_i_lldnoisedata",
#     "dx_205_alinity_i_mndhistory",
#     "dx_205_alinity_i_mndrecorddata",
#     "dx_205_alinity_i_navigateservicedata",
#     "dx_205_alinity_i_opticsrawdata",
#     "dx_205_alinity_i_oshealthmonitoringdata",
#     "dx_205_alinity_i_pipettorsyringebacklashdata",
#     "dx_205_alinity_i_pmrawdata",
#     "dx_205_alinity_i_reagentcoolerdata",
#     "dx_205_alinity_i_reagentoperation",
#     "dx_205_alinity_i_scripting",
#     "dx_205_alinity_i_teknicmotor",
#     "dx_205_alinity_i_temperaturedata",
#     "dx_205_alinity_i_vacuumpressuredata",
#     "dx_205_alinity_i_wambulkdata",
#     "dx_205_alinity_i_wamdata"
# )
#

dx.tbls <- c(
    "dx_architect_assay",
    "dx_architect_assayparams",
    "dx_architect_cal",
    "dx_architect_history",
    "dx_architect_lls",
    "dx_architect_maint",
    "dx_architect_optics",
    "dx_architect_pm",
    "dx_architect_post",
    "dx_architect_qc",
    "dx_architect_releasedqc",
    "dx_architect_results",
    "dx_architect_sample",
    "dx_architect_wam",
    "dx_a3600_control",
    "dx_a3600_counter",
    "dx_a3600_dream",
    "dx_a3600_error",
    "dx_a3600_lis",
    "dx_a3600_pass",
    "dx_a3600_process",
    "dx_a3600_uif",
    "dx_aps_counter",
    "dx_aps_error"
)

common_utils_path <- file.path(".", "common_utils.R")
if ( ! file.exists(common_utils_path)) {
    if (nchar(Sys.getenv("DEV_ROOT")) == 0) {
        stop("No 'common_utils.R' found")
    }
    common_utils_path <- file.path(Sys.getenv("DEV_ROOT"),
                                   "rlib",
                                   "common_utils.R")
    if ( ! file.exists(common_utils_path)) {
        stop("No DEV_ROOT 'common_utils.R' found")
    }
}
source(common_utils_path)

config_filename <- "config.csv"
if ( ! file.exists(config_filename)) {
    if (nchar(Sys.getenv("DEV_ROOT")) == 0) {
        stop("No 'config.file' found")
    }
    config_filename <- file.path(Sys.getenv("DEV_ROOT"),
                                 "config",
                                 "dx",
                                 "config.csv")
    if ( ! file.exists(config_filename)) {
        stop("No DEV_ROOT 'config.file' found")
    }
}

config <- read_csv_file(filename=config_filename,
                        type_of_file="Configuration")

rownames(config) <- config[,1]

sink("out2.log")

db_conn <- dx_connect_to_db(config)

now = Sys.Date()
test_date_format <- "%Y-%m-%d"
now_string <- format(now, test_date_format)

for (dx.tbl in dx.tbls) {
    print(sprintf("DX TBL ... %s", dx.tbl))
    query <- sprintf("select max(transaction_date) as max_day from dx.%s where transaction_date <= '%s'", dx.tbl, now_string)
    print(sprintf("DX TBL QUERY ... %s", query))
    tryCatch({
            print(dbGetQuery(db_conn, query))
        },
        error=function(e) { print(e); }
    )
}

dbDisconnect(db_conn)
#
sink()
#
q(status=0)

