
ifndef ROOT
ROOT = $(PWD)
endif

RLIB_DIRS = rlib

ATHENA_DIRS = \
	athena \
	athena_flat

SPARK_DIRS = \
	spark \
	spark_flat

SUB_DIRS = $(ATHENA_DIRS) spark_flat

include $(ROOT)/build/makefile.subdirs

