#!/bin/bash

source /opt/intel/computer_vision_sdk/bin/setupvars.sh

SRC_FOLDER=/home/aiuser/ai-workspace/experiments/NCS2/src
DATA_FOLDER=/home/aiuser/ai-workspace/experiments/NCS2/data
MODELS_FOLDER=/home/aiuser/ai-workspace/experiments/NCS2/models
VIDEOS_FOLDER=/home/aiuser/ai-workspace/experiments/NCS2/videos


python3 $SRC_FOLDER/NCS2_001_Image_PersonDetection.py -m $MODELS_FOLDER/pedestrian/rmnet_ssd/0013/dldt/person-detection-retail-0013-fp16.xml -d MYRIAD -i $VIDEO_FOLDER/bus_station_6094_960x540.mp4
