
-- Head Down Failure DCM 1006,186,MODULE,DCM
-- Head Down Failure DCM 1006,186,ERROR_CODE_VALUE,1006
-- Head Down Failure DCM 1006,186,IHN_LEVEL3_DESC,Head Down Failure DCM 1006
-- Head Down Failure DCM 1006,186,ALGORITHM_TYPE,ERROR_COUNT
-- Head Down Failure DCM 1006,186,ERROR_COUNT,4
-- Head Down Failure DCM 1006,186,THRESHOLD_DESCRIPTION,4/day for 2 consecutive days
-- Head Down Failure DCM 1006,186,THRESHOLDS_DAYS,2
-- Head Down Failure DCM 1006,186,THRESHOLD_DATA_DAYS,2

-- 'ALGORITHM_TYPE' AS ALGORITHM_TYPE,
-- 'ERROR_CODE_VALUE' AS PATTERN_DESCRIPTION,
-- 'ERROR_COUNT' AS THRESHOLD_NUMBER,
-- 'IHN_LEVEL3_DESC' AS THRESHOLD_ALERT,
-- 'THRESHOLD_DATA_DAYS' AS THRESHOLD_DATA_DAYS,
-- 'THRESHOLDS_DAYS' AS THRESHOLD_NUMBER_UNIT,
-- 'THRESHOLD_DESCRIPTION' AS THRESHOLD_NUMBER_DESC,
-- 'MODULE' AS MODULE_TYPE))

-- FOR TE IN THRESHOLD_COUNTS (DD.SN,                    --       V_SN1             VARCHAR2,
--                             TH.MODULE_TYPE,           --       V_NODETYPE1       VARCHAR2,
--                             TH.PATTERN_DESCRIPTION,   --       V_ERRORCODE1      VARCHAR2,
--                             DD.MIN_COMPL_DATE,        --       V_START_DATE      DATE,
--                             DD.MAX_COMPL_DATE,        --       V_END_DATE        DATE,
--                             TH.THRESHOLD_NUMBER_UNIT, --       V_DATA_DAYS       NUMBER,
--                             V_SAMP_ID_CHK1,           --       V_SAMP_ID_CHK1    VARCHAR2,
--                             V_SAMP_ID_CHK2)           --       V_SAMP_ID_CHK2    VARCHAR2)

SELECT 
    ASI.DEVICEID,
    ASI.SYSTEMSN,
    N.PL,
    N.SN,
    TRUNC (COMPLETIONDATE) FLAG_DATE,
    AE.NODETYPE,
    AE.ERRORCODE,
    AE.NODEID,
    AE.INSTANCEID,
    AC.TUBES_TODAY,
    MAX (AE.COMPLETIONDATE) MAX_COMPL_DATE,
    COUNT (AE.ERRORCODE) ERROR_COUNT,
    TRUNC ( (COUNT (AE.ERRORCODE) * 100 / AC.TUBES_TODAY), 2) ERROR_PERCENTAGE
FROM 
    SVC_PHM_ODS.PHM_ODS_A3600_ERRORS AE,
    A3600_LAYOUT_NODES_PL_SN N,
    IDAOWNER.A3600SYSTEMINFORMATION ASI,
    IDAOWNER.A3600_COUNTERS AC
WHERE
    AE.LAYOUT_NODES_ID = N.LAYOUT_NODES_ID
AND 
    N.CANID = AE.NODEID
AND 
    N.NODETYPE = AE.NODETYPE
-- AND 
    -- LOWER (N.SN) = LOWER (V_SN1)
AND 
    ASI.SYSTEMINFOID = N.SYSTEMINFOID
AND 
    AC.LAYOUT_NODES_ID = N.LAYOUT_NODES_ID
AND 
    AC.NODETYPE = AE.NODETYPE
AND 
    AC.COUNTER_DATE = TRUNC (AE.COMPLETIONDATE)
AND 
    AC.NODEID = AE.NODEID
AND 
    AC.INSTANCEID = AE.INSTANCEID
AND 
    N.SYSTEMINFOID = ASI.SYSTEMINFOID
AND 
    ASI.CURRENT_ROW = 'Y'
AND 
    AC.TUBES_TODAY <> 0
AND 
    (('DCM' != '%' AND AE.NODETYPE = 'DCM') OR 
     ('DCM' = '%' AND AE.NODETYPE LIKE 'DCM'))
AND 
    AE.ERRORCODE = '1006'
AND 
    NVL(AE.SAMPLEID, ' ') LIKE NVL('%', AE.SAMPLEID)
AND 
    ((TO_DATE('24-OCT-2019') - 2 + 1) <= AE.COMPLETIONDATE)
and 
    (AE.COMPLETIONDATE < TO_DATE('25-OCT-2019'))
GROUP BY 
    ASI.DEVICEID,
    ASI.SYSTEMSN,
    N.PL,
    N.SN,
    TRUNC (COMPLETIONDATE),
    AE.NODETYPE,
    AE.ERRORCODE,
    AE.NODEID,
    AE.INSTANCEID,
    AC.TUBES_TODAY
