-- 
--    CURSOR THRESHOLD_COUNTS (
--       V_SN1             VARCHAR2,
--       V_NODETYPE1       VARCHAR2,
--       V_ERRORCODE1      VARCHAR2,
--       V_START_DATE      DATE,
--       V_END_DATE        DATE,
--       V_DATA_DAYS       NUMBER,
--       V_SAMP_ID_CHK1    VARCHAR2,
--       V_SAMP_ID_CHK2    VARCHAR2)
--    IS
-- 

SELECT 
    ASI.DEVICEID,
    ASI.SYSTEMSN,
    N.PL,
    N.SN,
    TRUNC (COMPLETIONDATE) FLAG_DATE,
    AE.NODETYPE,
    AE.ERRORCODE,
    AE.NODEID,
    AE.INSTANCEID,
    AC.TUBES_TODAY,
    MAX (AE.COMPLETIONDATE) MAX_COMPL_DATE,
    COUNT (AE.ERRORCODE) ERROR_COUNT,
    TRUNC ( (COUNT (AE.ERRORCODE) * 100 / AC.TUBES_TODAY), 2) ERROR_PERCENTAGE
FROM 
    SVC_PHM_ODS.PHM_ODS_A3600_ERRORS AE,
    A3600_LAYOUT_NODES_PL_SN N,
    IDAOWNER.A3600SYSTEMINFORMATION ASI,
    IDAOWNER.A3600_COUNTERS AC
WHERE
    AE.LAYOUT_NODES_ID = N.LAYOUT_NODES_ID
AND
    N.CANID = AE.NODEID
AND
    N.NODETYPE = AE.NODETYPE
AND
    LOWER (N.SN) = LOWER (V_SN1)
AND
    ASI.SYSTEMINFOID = N.SYSTEMINFOID
AND
    AC.LAYOUT_NODES_ID = N.LAYOUT_NODES_ID
AND
    AC.NODETYPE = AE.NODETYPE
AND
    AC.COUNTER_DATE = TRUNC (AE.COMPLETIONDATE)
AND
    AC.NODEID = AE.NODEID
AND
    AC.INSTANCEID = AE.INSTANCEID
AND
    N.SYSTEMINFOID = ASI.SYSTEMINFOID
AND
    ASI.CURRENT_ROW = 'Y'
AND
    AC.TUBES_TODAY <> 0
AND
    ((V_NODETYPE1 != '%' AND AE.NODETYPE = V_NODETYPE1) OR 
     (V_NODETYPE1 = '%' AND AE.NODETYPE LIKE V_NODETYPE1))
AND
    AE.ERRORCODE = V_ERRORCODE1
AND
    NVL (AE.SAMPLEID, V_SAMP_ID_CHK1) LIKE
    NVL (V_SAMP_ID_CHK2, AE.SAMPLEID)
AND
    AE.COMPLETIONDATE BETWEEN V_START_DATE - V_DATA_DAYS + 1
AND
    V_END_DATE
GROUP BY
    ASI.DEVICEID,
    ASI.SYSTEMSN,
    N.PL,
    N.SN,
    TRUNC (COMPLETIONDATE),
    AE.NODETYPE,
    AE.ERRORCODE,
    AE.NODEID,
    AE.INSTANCEID,
    AC.TUBES_TODAY
