
ifndef ROOT
ROOT = $(PWD)/..
endif

SUB_DIRS = \
	architect_cc_cuvette_combined \
	architect_dark_counts_gt_avg250 \
	architect_dark_counts_gt_sd100 \
	architect_fe_pressure \
	architect_wam_a \
	architect_wam_b \
	architect_wam_c \
	cc_cuvette_integrity \
	cc_cuvette_wash \
	ia_dark_counts \
	ia_fe_pressure \
	ia_itv \
	ia_pipettor_sample_syringe_backlash \
	ia_process_jams_5756 \
	ia_process_jams_5758 \
	ia_vacuum_leak \
	ia_vacuum_pump \
	ia_vacuum_sensor \
	ia_washzone_aspiration

include $(ROOT)/build/makefile.subdirs
