    SELECT 
        PTT.PHM_THRESHOLDS_SK,
        PTT.THRESHOLD_NUMBER,
        PTT.THRESHOLD_NUMBER_UNIT,
        PTT.THRESHOLD_NUMBER_DESC,
        PP.PHM_PATTERNS_SK,
        PP.PATTERN_DESCRIPTION,
        PTT.THRESHOLD_ALERT,
        PTT.THRESHOLD_TYPE, 
        PTT.THRESHOLD_DATA_DAYS
    FROM 
        svc_phm_owner.PHM_PATTERNS PP, 
        svc_phm_owner.PHM_THRESHOLDS PTT 
    WHERE 
        PP.PHM_PATTERNS_SK = PTT.PHM_PATTERNS_SK
    AND 
        PP.PHM_ALGORITHM_DEFINITIONS_SK = PTT.PHM_ALGORITHM_DEFINITIONS_SK 
    AND 
        PP.PHM_ALGORITHM_DEFINITIONS_SK = 1001

