SELECT
    V.DEVICEID,
    V.MODULESN,
    AVG(V.ADCVALUE) AS MEAN_ADC,
    COUNT(V.ADCVALUE) AS NUM_READINGS
FROM 
    IDAQOWNER.DX_205_VACUUMPRESSUREDATA V
WHERE
    TO_TIMESTAMP('01/01/2019 00:00:00', 
                 'MM/DD/YYYY HH24:MI:SS') <= V.LOGDATE_LOCAL
AND 
    V.LOGDATE_LOCAL < TO_TIMESTAMP('02/01/2019 00:00:00', 
                                   'MM/DD/YYYY HH24:MI:SS')
AND
    V.VACUUMSTATENAME = 'VacuumBledOff'
GROUP BY
    V.DEVICEID,
    V.MODULESN
HAVING (
    AVG(V.ADCVALUE) <= 3549
AND 
    COUNT(V.ADCVALUE) >= 3
)
ORDER BY
    V.DEVICEID,
    V.MODULESN

