SELECT 
    W.WZPROBE,
    NVL(SUBSTR(W.WZPROBE,1,1),'NA') as WZ,
    NVL(SUBSTR(W.WZPROBE,3,1),'NA') as PRB,
    CASE WHEN W.PHM_PRODUCT_LINE_CODE = '117' 
         THEN 'i1SR' 
         WHEN W.PHM_PRODUCT_LINE_CODE = '116' 
         THEN 'i2SR'
         WHEN W.PHM_PRODUCT_LINE_CODE = '115' 
         THEN 'i2' 
    END  as MTYPE
FROM 
    PHM_WAM_OUTPUT_1 W
where 
    rownum < 1000
and
    W.PHM_PRODUCT_LINE_CODE = '115' 
